### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by alem0lars** [wannesm/wmgraphviz.vim#13]
I've installed the plugin with: `NeoBundle 'wannesm/wmgraphviz.vim'`.
However trying to type commands (like `:GraphvizCompile`, etc..) doesn't work out-of-the-box.

It's strange but it works only if I `set` something before (e.g. `:set verbose=0`) or something else. Otherwise it just doesn't do anything.

In any case, the commands completion doesn't work.

The only thing working out-of-the-box is omnifunc.

**Comment by exapsy** [comment]
This is still an issue :( Using Vundle. Wonder if anyone has any good ideas why is this an issue.

Edit:
Never mind, the README kinda says that the support is only for `Pathogen` as it's the only listed Plugin Manager.
which likely means that Vundle and NeoBundle or any other plugin manager is out of the picture judging from the fact that the plugin doesnt work at all on those.
