### ISSUE TITLE
mac GraphvizInteractive() not work

### ISSUE THREAD

**Issue by ghost** [wannesm/wmgraphviz.vim#22]
In my macbook, GraphvizInteractive() not work well
can you stand for it.

**Comment by wannesm** [comment]
Please add a more detailled bug report.

**Comment by realshovanshah** [comment]
@wannesm The issue is basically that `:GraphvizInteractive` doesn't work on MacOS. Something related to `Xlib` not being supported on Darwin. I'm not that educated on the issue.
